csc_io(l)

NAME
	csc_io

DESCRIPTION
	I/O Subsystem

FUNCTIONS
	CSCioInfoPrint     - formatted write to stdout
	CSCioWarnPrint     - formatted write to stdout
	CSCioErrorPrint    - formatted write to stderr
	CSCioSoftwareError - print a parameterized software error message
	CSCioRead          - read a specific number of bytes
	CSCioReadLine      - read bytes that are terminated by a newline
	CSCioBufWrite      - write an ASCII buffer
	CSCioBufRead       - read an ASCII buffer
