
#line 3 "lex.cpyy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cpyy_create_buffer
#define yy_delete_buffer cpyy_delete_buffer
#define yy_flex_debug cpyy_flex_debug
#define yy_init_buffer cpyy_init_buffer
#define yy_flush_buffer cpyy_flush_buffer
#define yy_load_buffer_state cpyy_load_buffer_state
#define yy_switch_to_buffer cpyy_switch_to_buffer
#define yyin cpyyin
#define yyleng cpyyleng
#define yylex cpyylex
#define yylineno cpyylineno
#define yyout cpyyout
#define yyrestart cpyyrestart
#define yytext cpyytext
#define yywrap cpyywrap
#define yyalloc cpyyalloc
#define yyrealloc cpyyrealloc
#define yyfree cpyyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cpyyrestart(cpyyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int cpyyleng;

extern FILE *cpyyin, *cpyyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cpyytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cpyytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cpyyrestart()), so that the user can continue scanning by
	 * just pointing cpyyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cpyytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int cpyyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow cpyywrap()'s to do buffer switches
 * instead of setting up a fresh cpyyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void cpyyrestart (FILE *input_file  );
void cpyy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cpyy_create_buffer (FILE *file,int size  );
void cpyy_delete_buffer (YY_BUFFER_STATE b  );
void cpyy_flush_buffer (YY_BUFFER_STATE b  );
void cpyypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void cpyypop_buffer_state (void );

static void cpyyensure_buffer_stack (void );
static void cpyy_load_buffer_state (void );
static void cpyy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cpyy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cpyy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cpyy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cpyy_scan_bytes (yyconst char *bytes,int len  );

void *cpyyalloc (yy_size_t  );
void *cpyyrealloc (void *,yy_size_t  );
void cpyyfree (void *  );

#define yy_new_buffer cpyy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cpyyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cpyy_create_buffer(cpyyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cpyyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cpyy_create_buffer(cpyyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cpyywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *cpyyin = (FILE *) 0, *cpyyout = (FILE *) 0;

typedef int yy_state_type;

extern int cpyylineno;

int cpyylineno = 1;

extern char *cpyytext;
#define yytext_ptr cpyytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cpyytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	cpyyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 41
#define YY_END_OF_BUFFER 42
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[311] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   42,   41,   31,   32,   33,   36,   40,   35,
       34,   37,   38,   39,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   34,   40,   40,
       31,   33,   40,   34,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,    2,   40,   34,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   34,
       40,    5,    5,   40,   40,   40,    6,   40,   40,   40,

       40,   40,    0,   40,   40,   40,   40,   40,   40,   13,
        0,   40,   40,   40,   40,    0,   34,   40,   40,    5,
       40,    5,   40,   40,    0,    0,    0,   40,   40,   40,
        0,   40,   40,   40,   40,   40,   40,   40,    0,   40,
        0,    0,   40,    0,    0,   40,    5,    5,    5,   40,
       40,    0,    0,    0,   40,   40,   40,    0,   14,   40,
        4,    0,   40,    0,   40,    0,   40,    0,    0,    0,
        0,    0,   40,   40,    5,    3,    0,    0,    0,    0,
       40,   40,   40,    0,    0,    0,    0,    0,    0,   12,
        0,   40,    0,    0,    0,   29,   28,   40,   40,    0,

        0,    0,    0,    0,   22,   40,   40,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   40,   40,
        0,    0,   30,   25,   26,   40,    1,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    5,   40,
        0,    0,   40,    0,    0,    0,    0,    0,    9,    0,
        0,    0,   24,    0,    5,   27,    0,   40,   19,    0,
        0,    0,   10,   18,    0,    0,    0,    5,    0,    0,
        0,    0,   15,   23,   21,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        7,    0,   20,    8,    0,    0,   16,    0,    0,   17,

        0,    0,    0,    0,    0,    0,    0,    0,   11,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    6,    7,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   10,   11,    1,
        1,    1,    1,    1,   12,   12,   12,   12,   12,   12,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        1,    1,    1,    1,   14,    1,   15,   16,   17,   18,

       19,   20,   21,   13,   22,   13,   13,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   13,   37,    1,   38,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[39] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    3,    3,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1
    } ;

static yyconst flex_int16_t yy_base[316] =
    {   0,
        0,   38,   62,    0,   97,  135,  165,    0,    0,    0,
        0,    0,  421,  422,  418,  422,    0,  422,    0,  422,
      410,  422,  422,  422,  400,    0,    0,  386,  389,  386,
        1,    2,  395,  383,  397,  389,    3,  177,  400,  400,
      406,    0,    0,  398,  388,  381,  382,    8,    3,  376,
      371,  382,  373,   20,  374,  371,  374,  372,  376,  371,
      375,  383,   43,  189,  201,  382,  380,  360,  373,  369,
      368,  370,  366,    5,  364,  376,  359,  360,  357,  356,
      358,  344,  357,  368,  351,  345,  342,  348,  363,  213,
      359,  227,   47,  348,  344,  359,    0,  358,  357,  337,

      332,  331,  329,  332,    0,  339,  331,  321,  335,    0,
      323,  335,  345,  344,  331,   29,   51,  338,  338,  239,
      336,   55,  315,  319,  312,  316,  315,  318,  315,  318,
      318,  311,  306,  299,  327,  314,  325,  300,  310,  306,
      312,  309,  319,  305,  297,   56,  251,  315,  311,  290,
      313,  296,  292,  291,  284,  299,  298,  283,    0,  305,
      304,  292,  302,  276,  275,  276,  273,  285,  279,  278,
      272,  276,  289,   59,  287,    0,   44,  272,  272,  271,
      257,  261,  274,  257,  266,  270,  261,  255,  263,    0,
      251,  277,  264,  266,  257,  422,  422,   63,  258,  242,

      247,  242,  217,  216,    0,  228,  230,  222,  218,  219,
      211,  205,  202,  205,  197,  186,  184,  192,  194,   64,
      172,  176,  422,  422,  422,  173,    0,  162,  170,  165,
      155,  154,  157,  142,  145,  150,  138,  148,  157,  158,
      133,  144,  137,  131,  141,  140,  136,  138,  422,  126,
      132,  124,  422,  147,  143,  422,  145,  144,  422,  142,
      126,  102,  422,  422,   96,  101,   99,    0,   99,  102,
       96,  111,  422,  422,  422,  103,  105,   98,  100,   90,
       96,   90,   95,   93,   94,   96,   81,   77,   93,   84,
      422,   90,  422,  422,   71,   61,   80,   55,   61,  422,

       57,   50,   60,   49,   54,   40,   34,   10,  422,  422,
      271,  274,  277,   11,    4
    } ;

static yyconst flex_int16_t yy_def[316] =
    {   0,
      311,  311,    2,    3,  312,  312,    2,    7,    2,    2,
        2,    2,  310,  310,  310,  310,  313,  310,  314,  310,
      314,  310,  310,  310,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  315,  314,  314,   38,
      310,  313,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  315,   38,   38,   64,   65,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,   64,
       90,   90,   92,  314,  314,  314,  314,  314,  314,  314,

      314,  314,  310,  314,  314,  314,  314,  314,  314,  314,
      310,  314,  314,  314,  314,  310,  314,  314,  314,   92,
       65,  120,  314,  314,  310,  310,  310,  314,  314,  314,
      310,  314,  314,  314,  314,  314,  314,  314,  310,  314,
      310,  310,  314,  310,  310,  314,  120,  147,   65,  314,
      314,  310,  310,  310,  314,  314,  314,  310,  314,  314,
      314,  310,  314,  310,  314,  310,  314,  310,  310,  310,
      310,  310,  314,  314,  314,  314,  310,  310,  310,  310,
      314,  314,  314,  310,  310,  310,  310,  310,  310,  314,
      310,  314,  310,  310,  310,  310,  310,  314,  314,  310,

      310,  310,  310,  310,  314,  314,  314,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  314,  314,
      310,  310,  310,  310,  310,  314,  314,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  314,  314,
      310,  310,  314,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  314,  310,  310,  314,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  314,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,

      310,  310,  310,  310,  310,  310,  310,  310,  310,    0,
      310,  310,  310,  310,  310
    } ;

static yyconst flex_int16_t yy_nxt[461] =
    {   0,
       14,   15,   16,   17,   18,   14,   63,   20,   21,   43,
       22,   62,   43,   43,   48,   53,   43,  310,  133,   54,
       55,  134,   74,   56,   49,   46,  100,   57,  309,   71,
      101,   47,   72,   75,   73,   80,   23,   24,   14,   15,
       16,   17,   18,   14,   81,   20,   21,   82,   22,   43,
      308,   62,   43,   43,  307,  122,   43,  144,  145,   44,
       65,   43,  173,  148,  174,  173,  200,  199,  201,  219,
      219,  220,  240,  306,   23,   24,   25,  305,  304,   26,
      303,  302,  301,   27,  300,  299,   28,   29,   30,  298,
       31,   32,   33,   34,   35,  297,   36,   14,   15,   16,

       17,   18,   14,   19,   20,   21,   19,   22,  296,  295,
       19,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,   23,   24,   14,   15,   16,   17,   18,
       14,   19,   20,   21,   19,   22,  272,  271,   19,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  219,  255,  254,  253,  252,  251,
      250,   23,   24,   38,   39,  249,   40,  248,  247,   40,
       40,   40,   40,   40,   40,   64,   65,  246,   66,  245,
      244,   66,   66,   66,   66,   66,   66,   90,  243,  242,

       91,  241,  239,   91,   91,   91,   91,   91,   91,   92,
       67,  238,   93,  237,  236,   93,   93,   93,   93,   93,
       93,  117,  235,  234,  118,  233,  232,  118,  118,  118,
      118,  118,  118,  119,  231,  120,  121,  230,  122,  229,
      228,  122,  122,  122,  122,  122,  122,  147,  227,  226,
      148,  225,  224,  148,  148,  148,  148,  148,  148,  175,
      223,  222,  175,  221,  173,  175,  175,  175,  175,  175,
      175,   19,   19,   19,   37,   37,   37,   42,  218,   42,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  121,  198,  197,  196,

      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
       43,   43,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  146,   65,  143,  142,
      141,  140,  139,  138,  137,  136,  135,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  118,  116,  115,
      114,  113,  112,  111,  110,  109,  108,  107,  106,  105,
      104,  103,  102,   99,   98,   97,   96,   95,   94,   43,
       91,   62,   89,   88,   87,   86,   85,   84,   83,   79,

       78,   77,   76,   70,   69,   68,   44,   41,   66,   67,
       61,   60,   59,   58,   52,   51,   50,   45,   44,   41,
      310,   13,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310
    } ;

static yyconst flex_int16_t yy_chk[461] =
    {   0,
        1,    1,    1,    1,    1,    1,  315,    1,    1,   37,
        1,   37,   37,  314,   27,   31,   37,    0,  105,   31,
       32,  105,   49,   32,   27,   26,   74,   32,  308,   48,
       74,   26,   48,   49,   48,   54,    1,    1,    2,    2,
        2,    2,    2,    2,   54,    2,    2,   54,    2,   63,
      307,   63,   63,   93,  306,   93,   63,  116,  116,  117,
      117,  122,  146,  122,  146,  174,  177,  174,  177,  198,
      220,  198,  220,  305,    2,    2,    3,  304,  303,    3,
      302,  301,  299,    3,  298,  297,    3,    3,    3,  296,
        3,    3,    3,    3,    3,  295,    3,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,  292,  290,
        5,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  276,  272,  271,  270,  269,  267,
      266,  265,  262,    5,    5,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,  261,  260,    6,  258,
      257,  255,  254,  252,  251,  250,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,    6,    6,    7,    7,  233,    7,  232,  231,    7,
        7,    7,    7,    7,    7,   38,   38,  230,   38,  229,
      228,   38,   38,   38,   38,   38,   38,   64,  226,  222,

       64,  221,  219,   64,   64,   64,   64,   64,   64,   65,
       65,  218,   65,  217,  216,   65,   65,   65,   65,   65,
       65,   90,  215,  214,   90,  213,  212,   90,   90,   90,
       90,   90,   90,   92,  211,   92,   92,  210,   92,  209,
      208,   92,   92,   92,   92,   92,   92,  120,  207,  206,
      120,  204,  203,  120,  120,  120,  120,  120,  120,  147,
      202,  201,  147,  200,  199,  147,  147,  147,  147,  147,
      147,  311,  311,  311,  312,  312,  312,  313,  195,  313,
      194,  193,  192,  191,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  175,  173,  172,  171,

      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  130,  129,  128,
      127,  126,  125,  124,  123,  121,  119,  118,  115,  114,
      113,  112,  111,  109,  108,  107,  106,  104,  103,  102,
      101,  100,   99,   98,   96,   95,   94,   91,   89,   88,
       87,   86,   85,   84,   83,   82,   81,   80,   79,   78,
       77,   76,   75,   73,   72,   71,   70,   69,   68,   67,
       66,   62,   61,   60,   59,   58,   57,   56,   55,   53,

       52,   51,   50,   47,   46,   45,   44,   41,   40,   39,
       36,   35,   34,   33,   30,   29,   28,   25,   21,   15,
       13,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cpyy_flex_debug;
int cpyy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cpyytext;
#line 1 "client6_token.l"
/*	$Id: client6_token.l,v 1.1.1.1 2006/12/04 00:45:22 Exp $	*/
/*	ported from KAME: cftoken.l,v 1.15 2002/09/24 14:20:49 itojun Exp	*/
/*
 * Copyright (C) 2002 WIDE Project.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the project nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
#line 36 "client6_token.l"
#include <sys/types.h>
#include <sys/socket.h>

#include <netinet/in.h>
#include <arpa/inet.h>

#include <errno.h>
#include <syslog.h>
#include <string.h>
#ifdef HAVE_STDARG_H
#include <stdarg.h>
#else
#include <varargs.h>
#endif

#include "queue.h"
#include "dhcp6.h"
#include "config.h"
#include "common.h"
#include "cp.tab.h"

const char *configfilename;
int lineno = 1;

static int cpyy_first_time = 1;
static int cpyyerrorcount = 0;

 
#ifndef NOCONFIG_DEBUG
#define YYDEBUG 1

int cfdebug = 1;
#else
int cfdebug = 0;
#endif

static void cfdebug_print __P((char *, char *, int));
extern int cf_post_config __P((void));

extern int cpyyparse(void);
extern int cf_post_config(void);

#define DP(str) if (cfdebug) cfdebug_print(str, cpyytext, cpyyleng)
#define DECHO if (cfdebug) cfdebug_print(NULL, cpyytext, cpyyleng);
/* abbreviations */





#line 754 "lex.cpyy.c"

#define INITIAL 0
#define S_CNF 1
#define S_IFACE 2
#define S_ADDR 3
#define S_RNT 4
#define S_RBT 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cpyylex_destroy (void );

int cpyyget_debug (void );

void cpyyset_debug (int debug_flag  );

YY_EXTRA_TYPE cpyyget_extra (void );

void cpyyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *cpyyget_in (void );

void cpyyset_in  (FILE * in_str  );

FILE *cpyyget_out (void );

void cpyyset_out  (FILE * out_str  );

int cpyyget_leng (void );

char *cpyyget_text (void );

int cpyyget_lineno (void );

void cpyyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cpyywrap (void );
#else
extern int cpyywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( cpyytext, cpyyleng, 1, cpyyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( cpyyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( cpyyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, cpyyin))==0 && ferror(cpyyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(cpyyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cpyylex (void);

#define YY_DECL int cpyylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cpyytext and cpyyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 111 "client6_token.l"


	if (cpyy_first_time) {
		BEGIN S_CNF;
		cpyy_first_time = 0;
	}

	/* interface configuration */
#line 950 "lex.cpyy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! cpyyin )
			cpyyin = stdin;

		if ( ! cpyyout )
			cpyyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cpyyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cpyy_create_buffer(cpyyin,YY_BUF_SIZE );
		}

		cpyy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cpyytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 311 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 422 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 119 "client6_token.l"
{ DECHO; BEGIN S_IFACE; return (INTERFACE); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 120 "client6_token.l"
{
	DECHO;
	cpyylval.str = strdup(cpyytext);
	BEGIN S_CNF;
	return (IFNAME);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 127 "client6_token.l"
{ DECHO; BEGIN S_ADDR; return (ADDRESS); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 129 "client6_token.l"
{ DECHO; BEGIN S_ADDR; return (PREFIX); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 130 "client6_token.l"
{
	struct in6_addr addr;
	DECHO;
	if (inet_pton(AF_INET6, cpyytext, &addr) < 1) {
		dprintf(LOG_ERR, "invalid address in line %d", lineno);
		return (-1);
	}
	cpyylval.addr = addr;
	BEGIN S_CNF;
	return (IPV6ADDR);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 141 "client6_token.l"
{ DECHO; return (IAID); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 142 "client6_token.l"
{ DECHO; return (V_TIME); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 143 "client6_token.l"
{ DECHO; return (P_TIME); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 144 "client6_token.l"
{ DECHO; return (RENEW_TIME); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 145 "client6_token.l"
{ DECHO; return (REBIND_TIME); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 146 "client6_token.l"
{ DECHO; return (PREFIX_DELEGATION_INTERFACE); }
	YY_BREAK
/* request */
case 12:
YY_RULE_SETUP
#line 148 "client6_token.l"
{ DECHO; return (REQUEST); }
	YY_BREAK
/* send */
case 13:
YY_RULE_SETUP
#line 151 "client6_token.l"
{ DECHO; return (SEND); }
	YY_BREAK
/* DHCP options */
case 14:
YY_RULE_SETUP
#line 153 "client6_token.l"
{ DECHO; return (OPTION); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 155 "client6_token.l"
{ DECHO; return (RAPID_COMMIT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 156 "client6_token.l"
{ DECHO; return (PREFIX_DELEGATION); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 157 "client6_token.l"
{ DECHO; return (DNS_SERVERS); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 158 "client6_token.l"
{ DECHO; return (SIP_SERVERS); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 159 "client6_token.l"
{ DECHO; return (NTP_SERVERS); }
	YY_BREAK
/* generic options */
case 20:
YY_RULE_SETUP
#line 161 "client6_token.l"
{ DECHO; return (INFO_ONLY); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 162 "client6_token.l"
{ DECHO; return (TEMP_ADDR); }
	YY_BREAK
/* duration */
case 22:
YY_RULE_SETUP
#line 164 "client6_token.l"
{ DECHO; return (INFINITY); }
	YY_BREAK
/* Foxconn added start pling 08/26/2009 */
case 23:
YY_RULE_SETUP
#line 167 "client6_token.l"
{ DECHO; return (SOLICIT_ONLY); }
	YY_BREAK
/* Foxconn added start pling 08/26/2009 */
/* Foxconn added start pling 09/07/2010 */
case 24:
YY_RULE_SETUP
#line 171 "client6_token.l"
{ DECHO; return (USER_CLASS); }
	YY_BREAK
/* Foxconn added end pling 09/07/2010 */
/* Foxconn added start pling 09/21/2010 */
/* For DHCPv6 readylogo test, to request IANA only or IAPD only */
case 25:
YY_RULE_SETUP
#line 176 "client6_token.l"
{ DECHO; return (IANA_ONLY); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 177 "client6_token.l"
{ DECHO; return (IAPD_ONLY); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 178 "client6_token.l"
{ DECHO; return (DOMAIN_LIST); }
	YY_BREAK
/* Foxconn added end pling 09/21/2010 */
/* Foxconn added start pling 10/07/2010 */
case 28:
YY_RULE_SETUP
#line 182 "client6_token.l"
{ DECHO; return (XID_SOL); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 183 "client6_token.l"
{ DECHO; return (XID_REQ); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 184 "client6_token.l"
{ DECHO; return (DUID_TIME); }
	YY_BREAK
/* Foxconn added end pling 10/07/2010 */
/* misc */
case 31:
YY_RULE_SETUP
#line 188 "client6_token.l"
{ ; }
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 189 "client6_token.l"
{ lineno++; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 190 "client6_token.l"
{ DP("comment"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 191 "client6_token.l"
{
	DECHO;
	cpyylval.num = strtoll(cpyytext, NULL, 10);
	return (NUMBER);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 196 "client6_token.l"
{ DECHO; return (SLASH); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 197 "client6_token.l"
{ DECHO; return (COMMA); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 198 "client6_token.l"
{ DP("end of sentence"); return (EOS); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 199 "client6_token.l"
{ DP("begin of closure"); return (BCL); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 200 "client6_token.l"
{ DP("end of closure"); return (ECL); }
	YY_BREAK
/* generic string */
case 40:
YY_RULE_SETUP
#line 203 "client6_token.l"
{
		DECHO;
		cpyylval.str = strdup(cpyytext);
		return (STRING);
	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 209 "client6_token.l"
ECHO;
	YY_BREAK
#line 1278 "lex.cpyy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(S_CNF):
case YY_STATE_EOF(S_IFACE):
case YY_STATE_EOF(S_ADDR):
case YY_STATE_EOF(S_RNT):
case YY_STATE_EOF(S_RBT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed cpyyin at a new source and called
			 * cpyylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = cpyyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( cpyywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cpyytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cpyylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cpyyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cpyyrestart(cpyyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cpyyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 311 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 311 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 310);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up cpyytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cpyyrestart(cpyyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cpyywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cpyytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cpyyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        cpyyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cpyy_create_buffer(cpyyin,YY_BUF_SIZE );
	}

	cpyy_init_buffer(YY_CURRENT_BUFFER,input_file );
	cpyy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cpyy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cpyypop_buffer_state();
	 *		cpyypush_buffer_state(new_buffer);
     */
	cpyyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cpyy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (cpyywrap()) processing, but the only time this flag
	 * is looked at is after cpyywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cpyy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	cpyyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cpyy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cpyyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cpyy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cpyyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cpyy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	cpyy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cpyy_create_buffer()
 * 
 */
    void cpyy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cpyyfree((void *) b->yy_ch_buf  );

	cpyyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cpyyrestart() or at EOF.
 */
    static void cpyy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cpyy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cpyy_init_buffer was _probably_
     * called from cpyyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cpyy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cpyy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void cpyypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	cpyyensure_buffer_stack();

	/* This block is copied from cpyy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cpyy_switch_to_buffer. */
	cpyy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void cpyypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cpyy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cpyy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cpyyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)cpyyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cpyyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)cpyyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cpyyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cpyy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cpyyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cpyy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cpyy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cpyylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cpyy_scan_bytes() instead.
 */
YY_BUFFER_STATE cpyy_scan_string (yyconst char * yystr )
{
    
	return cpyy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cpyylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cpyy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cpyyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cpyy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cpyy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cpyy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cpyytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cpyytext[cpyyleng] = (yy_hold_char); \
		(yy_c_buf_p) = cpyytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		cpyyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int cpyyget_lineno  (void)
{
        
    return cpyylineno;
}

/** Get the input stream.
 * 
 */
FILE *cpyyget_in  (void)
{
        return cpyyin;
}

/** Get the output stream.
 * 
 */
FILE *cpyyget_out  (void)
{
        return cpyyout;
}

/** Get the length of the current token.
 * 
 */
int cpyyget_leng  (void)
{
        return cpyyleng;
}

/** Get the current token.
 * 
 */

char *cpyyget_text  (void)
{
        return cpyytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void cpyyset_lineno (int  line_number )
{
    
    cpyylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cpyy_switch_to_buffer
 */
void cpyyset_in (FILE *  in_str )
{
        cpyyin = in_str ;
}

void cpyyset_out (FILE *  out_str )
{
        cpyyout = out_str ;
}

int cpyyget_debug  (void)
{
        return cpyy_flex_debug;
}

void cpyyset_debug (int  bdebug )
{
        cpyy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cpyylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    cpyyin = stdin;
    cpyyout = stdout;
#else
    cpyyin = (FILE *) 0;
    cpyyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cpyylex_init()
     */
    return 0;
}

/* cpyylex_destroy is for both reentrant and non-reentrant scanners. */
int cpyylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cpyy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cpyypop_buffer_state();
	}

	/* Destroy the stack itself. */
	cpyyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cpyylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cpyyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *cpyyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cpyyfree (void * ptr )
{
	free( (char *) ptr );	/* see cpyyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 209 "client6_token.l"


static void
cfdebug_print(w, t, l)
	char *w, *t;
	int l;
{
	if (w)
		dprintf(LOG_DEBUG, "<%d>%s [%s] (%d)", yy_start, w, t, l);
	else
		dprintf(LOG_DEBUG, "<%d>[%s] (%d)", yy_start, t, l);
}

static void
cpyyerror0(int level, char *s, va_list ap)
{
	char ebuf[BUFSIZ], *bp, *ep;

	bp = ebuf;
	ep = ebuf + sizeof(ebuf);
	bp += snprintf(bp, ep - bp, "%s %d: ", configfilename, lineno);
	if (bp < ep)
		bp += vsnprintf(bp, ep - bp, s, ap);

	dprintf(level, ebuf);
}

void
cpyyerror(char *s, ...)
{
	va_list ap;
#ifdef HAVE_STDARG_H
	va_start(ap, s);
#else
	va_start(ap);
#endif
	cpyyerror0(LOG_ERR, s, ap);
	va_end(ap);
	cpyyerrorcount++;
}

void
cpyywarn(char *s, ...)
{
	va_list ap;
#ifdef HAVE_STDARG_H
	va_start(ap, s);
#else
	va_start(ap);
#endif
	cpyyerror0(LOG_WARNING, s, ap);
	va_end(ap);
}

int
cfparse(const char *conf)
{
	configfilename = conf;
	if ((cpyyin = fopen(configfilename, "r")) == NULL) {
		if (errno == ENOENT)
			return (0);
		dprintf(LOG_ERR, "cfparse: fopen(%s): %s",
			configfilename, strerror(errno));
		return (-1);
	}

	if (cpyyparse() || cpyyerrorcount) {
		if (cpyyerrorcount) {
			cpyyerror("fatal parse failure: exiting (%d errors)",
				cpyyerrorcount);
		} else
			cpyyerror("fatal parse failure: exiting");
		return (-1);
	}

	return (cf_post_config());
}

