#
# pppstats Makefile for SVR4 systems
# $Id: Makefile.sol2 241182 2011-02-17 21:50:03Z $
#

include ../solaris/Makedefs

CFLAGS = -DSTREAMS -I../include $(COPTS)

all: pppstats

pppstats: pppstats.c
	$(CC) $(CFLAGS) -o pppstats pppstats.c

install: pppstats
	$(INSTALL) -f $(BINDIR) pppstats
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppstats.8

clean:
	rm -f pppstats *~ core
